---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./echo/install.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/labels
        value:
          toolkit.fluxcd.io/tenant: devops-team
          istio.io/dataplane-mode: ambient
    target:
      version: v1
      kind: Namespace
      name: default
