---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../components
transformers:
  - labels.yaml
resources:
  - dapr-system
  - default
  - external-secrets
  - istio-system
  - keda
  - kube-system
  - kube-tools
