---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: percona-system
resources:
  - https://raw.githubusercontent.com/percona/percona-server-mongodb-operator/v1.21.1/deploy/bundle.yaml
